name: orca-master-bridge-ci (draft)

on:
  push:
    branches:
      - 'feature/orca-master-*'
  pull_request:
    branches:
      - 'feature/orca-master-*'

env:
  NODE_VERSION: '20'
  RUN_ID: ${{ github.run_id }}
  CI: true

jobs:
  qa:
    name: qa-${{ matrix.msw.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        msw:
          - name: msw-on
            msw_on: '1'
            orca_api_base: 'http://localhost:4173'
          - name: server-proxy
            msw_on: '0'
            orca_api_base: ${{ secrets.ORCA_API_BASE }}
    env:
      ORCA_API_BASE: ${{ matrix.msw.orca_api_base }}
      MSW_ON: ${{ matrix.msw.msw_on }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: web-client/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: web-client

      - name: Generate OpenAPI types (orca-master)
        run: |
          npm run openapi:orca-master
          git diff --quiet -- web-client/src/generated/orca-master.ts docs/server-modernization/phase2/operations/assets/openapi/orca-master-orca05-06-08.yaml || {
            mkdir -p artifacts/ci
            git diff -- web-client/src/generated/orca-master.ts docs/server-modernization/phase2/operations/assets/openapi/orca-master-orca05-06-08.yaml > artifacts/ci/openapi.diff
            exit 1
          }
        working-directory: web-client

      - name: Verify MSW fixtures metadata & hash
        run: |
          node scripts/verify-msw-fixtures.mjs \
            --fixtures web-client/src/mocks/fixtures/orcaMaster.ts \
            --require runId,snapshotVersion,dataSource,cacheHit,missingMaster,fallbackUsed \
            --expect-run-id "${RUN_ID}" \
            --expect-snapshot-version "${SNAPSHOT_VERSION}" \
            --hash-out artifacts/ci/msw-fixtures.sha256
        env:
          SNAPSHOT_VERSION: auto
          RUN_ID: ${{ env.RUN_ID }}

      - name: Seed template dry-run (psql ROLLBACK)
        env:
          SEED_DSN: ${{ secrets.ORCA_SEED_CHECK_DSN }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client
          mkdir -p artifacts/ci
          for f in artifacts/api-stability/20251124T130000Z/seed/templates/*.sql; do
            echo "-- file: $f" >> artifacts/ci/seed-dryrun.log
            { cat "$f"; echo "ROLLBACK;"; } | psql "$SEED_DSN" \
              --single-transaction \
              --no-psqlrc \
              --set ON_ERROR_STOP=1 \
              --set client_min_messages=warning \
              --echo-all >> artifacts/ci/seed-dryrun.log
          done

      - name: TypeScript typecheck
        run: npm run typecheck
        working-directory: web-client

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: orca-master-bridge-ci-${{ matrix.msw.name }}
          path: |
            artifacts/ci/**
            web-client/src/generated/orca-master.ts
