* Host localhost:8000 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8000...
* Connected to localhost (::1) port 8000
> GET /api11/unknown HTTP/1.1
> Host: localhost:8000
> Accept: application/json
> User-Agent: handbook-worker/1.0
> 
* Request completely sent off
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Date: Thu, 13 Nov 2025 12:43:06 GMT
< Content-Length: 53
< 
{ [53 bytes data]
* Connection #0 to host localhost left intact
{"Code":404,"Message":"code=404, message=Not Found"}
