GET /20/adm/phr/LOCAL.FACILITY.0001,00000001,20250101,20250101 HTTP/1.1
Host: weborca.cloud.orcamo.jp
X-Facility-Id: LOCAL.FACILITY.0001
X-Touch-TraceId: 20251226T060944Z
X-Access-Reason: phr11_container
Authorization: Basic <MASKED>
