GET /20/adm/phr/medication/WEB1001?docSince=2025-05-01 HTTP/1.1
Host: weborca.cloud.orcamo.jp
X-Facility-Id: LOCAL.FACILITY.0001
X-Touch-TraceId: 20251226T060944Z
X-Access-Reason: phr09_medication
Authorization: Basic <MASKED>
