HTTP/1.1 200 OK
Content-Type: application/xml; charset=UTF-8
X-Hybridmode: normal
Date: Thu, 13 Nov 2025 04:23:06 GMT
Transfer-Encoding: chunked

<?xml version="1.0" encoding="UTF-8"?>
<xmlio2>
<patientmodres type="record">
<Information_Date type="string">2025-11-13</Information_Date>
<Information_Time type="string">13:23:06</Information_Time>
<Api_Result type="string">P1</Api_Result>
<Api_Result_Message type="string">患者番号の桁数が違います。</Api_Result_Message>
<Reskey type="string">Acceptance_Info</Reskey>
<Patient_Information type="record">
<Patient_ID type="string">00000001</Patient_ID>
<WholeName type="string">Official Sample Taro</WholeName>
<WholeName_inKana type="string">OFISHARUSANPURUTARO</WholeName_inKana>
<BirthDate type="string">1990-05-12</BirthDate>
<Sex type="string">1</Sex>
<HouseHolder_WholeName type="string">Official Sample Household</HouseHolder_WholeName>
<Relationship type="string">1</Relationship>
<Occupation type="string">Engineer</Occupation>
<CellularNumber type="string">09055557777</CellularNumber>
<EmailAddress type="string">official-sample@example.com</EmailAddress>
<Home_Address_Information type="record">
<Address_ZipCode type="string">1500001</Address_ZipCode>
<WholeAddress1 type="string">Tokyo Shibuya Jingumae 1-2-3</WholeAddress1>
<PhoneNumber1 type="string">0311112222</PhoneNumber1>
</Home_Address_Information>
<HealthInsurance_Information type="array">
<HealthInsurance_Information_child type="record">
<InsuranceProvider_Class type="string">1</InsuranceProvider_Class>
<InsuranceProvider_Number type="string">06123456</InsuranceProvider_Number>
<InsuranceProvider_WholeName type="string">National Health Insu</InsuranceProvider_WholeName>
<HealthInsuredPerson_Symbol type="string">AP</HealthInsuredPerson_Symbol>
<HealthInsuredPerson_Number type="string">2109876</HealthInsuredPerson_Number>
<HealthInsuredPerson_Branch_Number type="string">00</HealthInsuredPerson_Branch_Number>
<RelationToInsuredPerson type="string">1</RelationToInsuredPerson>
<Certificate_StartDate type="string">2025-11-01</Certificate_StartDate>
</HealthInsurance_Information_child>
</HealthInsurance_Information>
</Patient_Information>
</patientmodres>
</xmlio2>