POST /20/adm/phr/identityToken HTTP/1.1
Host: weborca.cloud.orcamo.jp
X-Facility-Id: LOCAL.FACILITY.0001
X-Touch-TraceId: 20251226T060944Z
X-Access-Reason: phr06_identityToken
X-Consent-Token: 20251226T060944Z-consent
Content-Type: application/json; charset=UTF-8
Accept: application/json
Authorization: Basic <MASKED>
Body File: artifacts/orca-connectivity/20251226T060944Z/phr-seq/30_layer-id/identityToken/PHR-06_request.json
