GET /20/adm/phr/patient/WEB1001 HTTP/1.1
Host: weborca.cloud.orcamo.jp
X-Facility-Id: LOCAL.FACILITY.0001
X-Touch-TraceId: 20251226T060944Z
X-Access-Reason: phr10_patient
Authorization: Basic <MASKED>
