name: opendolphin_webclient
services:
  db:
    container_name: opendolphin-postgres
    environment:
      POSTGRES_DB: opendolphin
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5 --auth-local=trust
      POSTGRES_PASSWORD: opendolphin
      POSTGRES_USER: opendolphin
      TZ: Asia/Tokyo
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:14
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume: {}
  db-modernized:
    container_name: opendolphin-postgres-modernized
    environment:
      POSTGRES_DB: opendolphin_modern
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5 --auth-local=trust
      POSTGRES_PASSWORD: opendolphin
      POSTGRES_USER: opendolphin
      TZ: Asia/Tokyo
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:14
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5432
        published: "55432"
        protocol: tcp
    volumes:
      - type: volume
        source: postgres-data-modernized
        target: /var/lib/postgresql/data
        volume: {}
  server:
    build:
      context: /mnt/c/Users/marug/Documents/OpenDolphin_WebClient
      dockerfile: ops/legacy-server/docker/Dockerfile
    container_name: opendolphin-server
    depends_on:
      db:
        condition: service_healthy
        required: true
    environment:
      DB_HOST: db
      DB_NAME: opendolphin
      DB_PASSWORD: opendolphin
      DB_PORT: "5432"
      DB_SSLMODE: prefer
      DB_SSLROOTCERT: ""
      DB_USER: opendolphin
      FACTOR2_AES_KEY_B64: b3BlbmRvbHBoaW4tZGV2LWZhY3RvcjIta2V5LTMyYnl0ZXM=
      FIDO2_ALLOWED_ORIGINS: https://localhost:8443,http://localhost:8080
      FIDO2_RP_ID: localhost
      FIDO2_RP_NAME: OpenDolphin Dev
      PLIVO_AUTH_ID: ""
      PLIVO_AUTH_TOKEN: ""
      PLIVO_BASE_URL: https://api.plivo.com/v1/
      PLIVO_DEFAULT_COUNTRY: "+81"
      PLIVO_ENVIRONMENT: production
      PLIVO_LOG_LEVEL: NONE
      PLIVO_LOG_MESSAGE_CONTENT: "false"
      PLIVO_SOURCE_NUMBER: ""
      TZ: Asia/Tokyo
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -sf -H "userName: 1.3.6.1.4.1.9414.10.1:dolphin" -H "password: 36cdf8b887a5cffc78dcd5c08991b993" http://localhost:8080/openDolphin/resources/dolphin || exit 1'
      timeout: 10s
      interval: 30s
      retries: 5
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
      - mode: ingress
        target: 9990
        published: "9990"
        protocol: tcp
  server-modernized-dev:
    build:
      context: /mnt/c/Users/marug/Documents/OpenDolphin_WebClient
      dockerfile: ops/modernized-server/docker/Dockerfile
    container_name: opendolphin-server-modernized-dev
    depends_on:
      db-modernized:
        condition: service_healthy
        required: true
    environment:
      DB_HOST: db-modernized
      DB_NAME: opendolphin_modern
      DB_PASSWORD: opendolphin
      DB_PORT: "5432"
      DB_SSLMODE: prefer
      DB_SSLROOTCERT: ""
      DB_USER: opendolphin
      FACTOR2_AES_KEY_B64: b3BlbmRvbHBoaW4tZGV2LWZhY3RvcjIta2V5LTMyYnl0ZXM=
      FIDO2_ALLOWED_ORIGINS: https://localhost:8443,http://localhost:9080
      FIDO2_RP_ID: localhost
      FIDO2_RP_NAME: OpenDolphin Dev
      PLIVO_AUTH_ID: ""
      PLIVO_AUTH_TOKEN: ""
      PLIVO_BASE_URL: https://api.plivo.com/v1/
      PLIVO_DEFAULT_COUNTRY: "+81"
      PLIVO_ENVIRONMENT: production
      PLIVO_LOG_LEVEL: NONE
      PLIVO_LOG_MESSAGE_CONTENT: "false"
      PLIVO_SOURCE_NUMBER: ""
      TZ: Asia/Tokyo
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -sf -H "userName: 1.3.6.1.4.1.9414.10.1:dolphin" -H "password: 36cdf8b887a5cffc78dcd5c08991b993" http://localhost:8080/openDolphin/resources/dolphin || exit 1'
      timeout: 10s
      interval: 30s
      retries: 5
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "9080"
        protocol: tcp
      - mode: ingress
        target: 9990
        published: "9995"
        protocol: tcp
networks:
  default:
    name: opendolphin_webclient_default
volumes:
  postgres-data:
    name: opendolphin_webclient_postgres-data
  postgres-data-modernized:
    name: opendolphin_webclient_postgres-data-modernized
