POST /20/adm/phr/identityToken HTTP/1.1
Host: weborca-trial.orca.med.or.jp
X-Facility-Id: 1234567
X-Touch-TraceId: 20251121TrialPHRSeqZ1-CDE
X-Access-Reason: phr06_identityToken
X-Consent-Token: 20251121TrialPHRSeqZ1-CDE-consent
Content-Type: application/json; charset=UTF-8
Accept: application/json
Authorization: Basic trial/weborcatrial
Body File: artifacts/orca-connectivity/20251121TrialPHRSeqZ1-CDE/crud/phr_phase_cde/phr06_identityToken/request.json
Notes: RUN_ID=20251121TrialPHRSeqZ1-CDE
