# NOTE: GitHub Actions による週次 Dry-Run 定義（.github/workflows/java-time-sample.yml と同一内容）。
name: JavaTime Sample Dry-Run

on:
  schedule:
    # 毎週月曜 00:30 JST（UTC 15:30 日曜）
    - cron: '30 15 * * 0'
  workflow_dispatch:

jobs:
  java-time-dry-run:
    name: java-time-dry-run
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run java-time-sample.sh (--dry-run)
        id: run-script
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p tmp/java-time/logs
          DATE_STAMP="$(date +%Y%m%d)"
          OUTPUT_DIR="tmp/java-time/github-actions-${DATE_STAMP}"
          LOG_PATH="tmp/java-time/logs/github-actions-${DATE_STAMP}.log"
          export JAVA_TIME_OUTPUT_DIR="$OUTPUT_DIR"
          bash ops/monitoring/scripts/java-time-sample.sh --dry-run 2>&1 | tee "$LOG_PATH"
          echo "log_path=${LOG_PATH}" >> "${GITHUB_OUTPUT}"

      - name: Upload dry-run artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: java-time-dry-run-log
          path: |
            tmp/java-time/logs/
            tmp/java-time/github-actions-*
          if-no-files-found: warn
