PUT /20/adm/phr/accessKey HTTP/1.1
Host: localhost:9080
X-Facility-Id: LOCAL.FACILITY.0001
X-Trace-Id: 20251226T060944Z
X-Request-Id: 20251226T060944Z
X-Access-Reason: phr02_accessKey
userName: <MASKED>
password: <MASKED>
Accept: application/octet-stream
Content-Type: application/json; charset=UTF-8
Body File: artifacts/orca-connectivity/20251226T060944Z/phr-seq/10_key-management/PHR-02_request_modern.json
